name: CI

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo $PATH
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        CLAIR_ADDR=localhost:6060 /home/aj/Downloads/applications/klar-2.4.0-linux-amd64 arminc/clair-db:latest
