name: PR

on:
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
        
    - name: Docker build
      run: |
        docker build -f ${{ github.workspace }}/Dockerfile -t ajinkya599/scanrepo:quarantine .
        #docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_PASSWORD }}
        #docker push ajinkya599/scanrepo:quarantine

    - name: Container scan
      uses: shigupt202/local-container-scan@releases/v1
      with:
        image-name: ajinkya599/scanrepo:quarantine
