name: PR

on:
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
        
    - name: Docker build
      run: |
        docker build -f ${{ github.workspace }}/Dockerfile -t ajinkya599/scanrepo:beta-0.0 .

    - name: Container scan
      uses: Azure/container-scan@users/aj/check-run-through-app-dev
      with:
        image-name: ajinkya599/scanrepo:beta-0.0
